### PR TITLE
Suppress warnings using custom empty error handler instead of `@`

### LINKED ISSUE #49: `FileWriter::writeFile()` raises warnings (instead of exception) when permission to write to the target destination is denied
Taking these tests (and related SUT) from `ocramius/proxy-manager`:

```php

    public function testGenerateWillFailIfTmpFileCannotBeWrittenToDisk(): void
    {
        $tmpDirPath = $this->tempDir . '/' . uniqid('nonWritable', true);
        mkdir($tmpDirPath, 0555, true);

        $locator   = $this->createMock(FileLocatorInterface::class);
        $generator = new FileWriterGeneratorStrategy($locator);
        $tmpFile   = $tmpDirPath . '/' . uniqid('FileWriterGeneratorStrategyFailedFileWriteTest', true) . '.php';
        $namespace = 'Foo';
        $className = UniqueIdentifierGenerator::getIdentifier('Bar');
        $fqcn      = $namespace . '\\' . $className;

        $locator
            ->method('getProxyFileName')
            ->with($fqcn)
            ->willReturn($tmpFile);

        $this->expectException(FileNotWritableException::class);
        $generator->generate(new ClassGenerator($fqcn));
    }

    public function testGenerateWillFailIfTmpFileCannotBeMovedToFinalDestination(): void
    {
        $locator   = $this->createMock(FileLocatorInterface::class);
        $generator = new FileWriterGeneratorStrategy($locator);
        $tmpFile   = $this->tempDir . '/' . uniqid('FileWriterGeneratorStrategyFailedFileMoveTest', true) . '.php';
        $namespace = 'Foo';
        $className = UniqueIdentifierGenerator::getIdentifier('Bar');
        $fqcn      = $namespace . '\\' . $className;

        $locator
            ->method('getProxyFileName')
            ->with($fqcn)
            ->willReturn($tmpFile);

        mkdir($tmpFile);

        $this->expectException(FileNotWritableException::class);
        $generator->generate(new ClassGenerator($fqcn));
    }
```

```php
<?php

declare(strict_types=1);

namespace ProxyManager\GeneratorStrategy;

use Laminas\Code\Generator\ClassGenerator;
use ProxyManager\Exception\FileNotWritableException;
use ProxyManager\FileLocator\FileLocatorInterface;
use Webimpress\SafeWriter\Exception\ExceptionInterface as FileWriterException;
use Webimpress\SafeWriter\FileWriter;

/**
 * Generator strategy that writes the generated classes to disk while generating them
 *
 * {@inheritDoc}
 */
class FileWriterGeneratorStrategy implements GeneratorStrategyInterface
{
    protected FileLocatorInterface $fileLocator;

    public function __construct(FileLocatorInterface $fileLocator)
    {
        $this->fileLocator = $fileLocator;
    }

    /**
     * Write generated code to disk and return the class code
     *
     * {@inheritDoc}
     *
     * @throws FileNotWritableException
     */
    public function generate(ClassGenerator $classGenerator): string
    {
        $generatedCode = $classGenerator->generate();
        $className     = ((string) $classGenerator->getNamespaceName()) . '\\' . $classGenerator->getName();
        $fileName      = $this->fileLocator->getProxyFileName($className);

        try {
            FileWriter::writeFile($fileName, "<?php\n\n" . $generatedCode);

            return $generatedCode;
        } catch (FileWriterException $e) {
            throw FileNotWritableException::fromPrevious($e);
        }
    }
}
```

produces:

```
There were 2 failures:

1) ProxyManagerTest\GeneratorStrategy\FileWriterGeneratorStrategyTest::testGenerateWillFailIfTmpFileCannotBeWrittenToDisk
Failed asserting that exception of type "ErrorException" matches expected exception "ProxyManager\Exception\FileNotWritableException". Message was: "" at
/home/ocramius/Documents/ocramius/ProxyManager/tests/ProxyManagerTest/GeneratorStrategy/FileWriterGeneratorStrategyTest.php:53
/home/ocramius/Documents/ocramius/ProxyManager/vendor/webimpress/safe-writer/src/FileWriter.php:29
/home/ocramius/Documents/ocramius/ProxyManager/src/ProxyManager/GeneratorStrategy/FileWriterGeneratorStrategy.php:41
/home/ocramius/Documents/ocramius/ProxyManager/tests/ProxyManagerTest/GeneratorStrategy/FileWriterGeneratorStrategyTest.php:126
.

2) ProxyManagerTest\GeneratorStrategy\FileWriterGeneratorStrategyTest::testGenerateWillFailIfTmpFileCannotBeMovedToFinalDestination
Failed asserting that exception of type "ErrorException" matches expected exception "ProxyManager\Exception\FileNotWritableException". Message was: "" at
/home/ocramius/Documents/ocramius/ProxyManager/tests/ProxyManagerTest/GeneratorStrategy/FileWriterGeneratorStrategyTest.php:53
/home/ocramius/Documents/ocramius/ProxyManager/vendor/webimpress/safe-writer/src/FileWriter.php:51
/home/ocramius/Documents/ocramius/ProxyManager/src/ProxyManager/GeneratorStrategy/FileWriterGeneratorStrategy.php:41
/home/ocramius/Documents/ocramius/ProxyManager/tests/ProxyManagerTest/GeneratorStrategy/FileWriterGeneratorStrategyTest.php:146
```

To correct this, `set_error_handler(function () {})` and `restore_error_handler()` had to be used:

```php
<?php

declare(strict_types=1);

namespace ProxyManager\GeneratorStrategy;

use Closure;
use Laminas\Code\Generator\ClassGenerator;
use ProxyManager\Exception\FileNotWritableException;
use ProxyManager\FileLocator\FileLocatorInterface;
use Webimpress\SafeWriter\Exception\ExceptionInterface as FileWriterException;
use Webimpress\SafeWriter\FileWriter;

use function restore_error_handler;
use function set_error_handler;

/**
 * Generator strategy that writes the generated classes to disk while generating them
 *
 * {@inheritDoc}
 */
class FileWriterGeneratorStrategy implements GeneratorStrategyInterface
{
    protected FileLocatorInterface $fileLocator;
    private Closure $emptyErrorHandler;

    public function __construct(FileLocatorInterface $fileLocator)
    {
        $this->fileLocator       = $fileLocator;
        $this->emptyErrorHandler = static function (): void {
        };
    }

    /**
     * Write generated code to disk and return the class code
     *
     * {@inheritDoc}
     *
     * @throws FileNotWritableException
     */
    public function generate(ClassGenerator $classGenerator): string
    {
        $generatedCode = $classGenerator->generate();
        $className     = ((string) $classGenerator->getNamespaceName()) . '\\' . $classGenerator->getName();
        $fileName      = $this->fileLocator->getProxyFileName($className);

        set_error_handler($this->emptyErrorHandler);

        try {
            FileWriter::writeFile($fileName, "<?php\n\n" . $generatedCode);

            return $generatedCode;
        } catch (FileWriterException $e) {
            throw FileNotWritableException::fromPrevious($e);
        } finally {
            restore_error_handler();
        }
    }
}
```

### PR DESCRIPTION
**Pull request by michalbundyra**
Fixes #49

When we have a custom error handler around writeFile then the warning
can be handled in case directory os not writable, because warnings were
suppressed by `@` not a custom (empty) error handler.

### CODE REVIEW

File: src/FileWriter.php [hunk 1]
```diff
@@ -25,13 +29,18 @@ final class FileWriter
     public static function writeFile(string $file, string $content, int $chmod = 0666) : void
     {
         $dir = dirname($file);
+
         // suppress notice thrown when falling back to system temp dir
-        $tmp = @tempnam($dir, 'wsw');
+        $tmp = self::suppress(static function () use ($dir) {
```
Comment (Ocramius) [inline src/FileWriter.php:34]: The entire `set_error_handler()` stuff is a bit expensive - perhaps wrap everything within one big `self::suppress()`?

File: src/FileWriter.php [hunk 2]
```diff
@@ -25,13 +29,18 @@ final class FileWriter
...
+            return tempnam($dir, 'wsw');
+        });
 
         if ($tmp === false) {
             throw Exception\RuntimeException::unableToCreateTemporaryFile($dir);
         }
 
+        assert(is_string($tmp));
```
Comment (Ocramius) [inline src/FileWriter.php:42]: If the above block is simplified to `if (! \is_string($tmp)) {` then this assertion can be removed

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: test/FileWriterTest.php [hunk 3]
```diff
@@ -157,6 +160,24 @@ public function testUnwritableDirThrowsException() : void
...
+    {
+        /** @psalm-suppress InvalidArgument */
+        set_error_handler(static function () : void {
+            throw new ErrorException();
+        });
+
+        $dir = sys_get_temp_dir() . '/unwritable';
+        touch($dir);
+
+        $this->expectException(RuntimeException::class);
```
Comment (Ocramius) [inline test/FileWriterTest.php:173]: Don't we expect a `WriteContentException` here?

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: test/FileWriterTest.php (hunk 3 above)
Comment (michalbundyra) [reply test/FileWriterTest.php:173]: No, because we got the exception from:

```php
if (dirname($tmp) !== realpath($dir)) {
    unlink($tmp);
    throw Exception\RuntimeException::unableToCreateTemporaryFile($dir);
}
```

as `/tmp/unwritable` is non writable and script fallback to `/tmp` so these paths are different.

Comment (Ocramius) [reply test/FileWriterTest.php:173]: Ahh, never mind, I did not see that `RuntimeException` is part of this package, imported above :+1:

**Review by Ocramius — APPROVED** [review]
